[tool.poetry]
name = "DEMorphy"
version = "0.9.0"
description = ""
authors = ["Xpect AG <rnd@xpect.ai>"]
readme = "README.md"
packages = []

[tool.poetry.dependencies]
python = ">=3.9.16,<3.11"
dawg2 = "^0.9.0"
